env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  {
    "plugins": ["react-hooks"],
    "rules":
      {
        "react-hooks/rules-of-hooks": "error",
        "react-hooks/exhaustive-deps": "warn",
      },
  }
